version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: friday
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: weekly
    day: friday
  open-pull-requests-limit: 99
- package-ecosystem: npm
  directory: "/server/src/main/webapp/WEB-INF/rails"
  commit-message:
    prefix: ui
    prefix-development: ui-dev
  schedule:
    interval: weekly
    day: friday
  open-pull-requests-limit: 99
  groups:
    babel:
      patterns: ["@babel/*"]
    jasmine:
      patterns: ["jasmine*", "@types/jasmine*"]
    webpack:
      patterns: ["webpack*", "@types/webpack*", "*-loader", "*-webpack-plugin", "*mini-css-extract-plugin"]
      exclude-patterns: ["karma-*-loader"]
    types:
      patterns: ["@types/*"]
- package-ecosystem: bundler
  directory: "/server/src/main/webapp/WEB-INF/rails"
  commit-message:
    prefix: ui
    prefix-development: ui-dev
  schedule:
    interval: weekly
    day: friday
  open-pull-requests-limit: 99
  allow:
    - dependency-type: all
  groups:
    mail:
      patterns: ["mail", "net-*"]
    rspec:
      patterns: ["rspec*"]
    sass:
      patterns: ["sass*"]
