version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
- package-ecosystem: npm
  directory: "/server/src/main/webapp/WEB-INF/rails"
  commit-message:
    prefix: ui
    prefix-development: ui-dev
  schedule:
    interval: weekly
    day: friday
  open-pull-requests-limit: 99
- package-ecosystem: bundler
  directory: "/server/src/main/webapp/WEB-INF/rails"
  commit-message:
    prefix: ui
    prefix-development: ui-dev
  schedule:
    interval: weekly
    day: friday
  open-pull-requests-limit: 99
- package-ecosystem: npm
  directory: "/scripts"
  commit-message:
    prefix: dev-scripts
  schedule:
    interval: weekly
    day: friday
- package-ecosystem: bundler
  directory: "/scripts"
  schedule:
    interval: weekly
    day: friday
  commit-message:
    prefix: dev-scripts
