waitSeconds: 5
preserveLicenseComments: false
optimize: 'uglify2'
optimizeCss: 'none'
normalizeDirDefines: 'all'
generateSourceMaps: true
useSourceUrl: true

paths:
  es5shim: 'lib/es5-shim'
  es6shim: 'lib/es6-shim'
  angular: 'lib/angular-1.0.8'
  jquery: 'lib/jquery-2.2.0'
  jquery.textcomplete: 'lib/jquery.textcomplete-0.8.1'
  mithril: 'lib/mithril-0.2.5'
  lodash: 'lib/lodash'
  lodash-inflection: 'lib/lodash-inflection'
  filesize: 'lib/filesize'
  dragula: 'lib/dragula-3.1.0'
  js-routes: 'js-routes'
  string: 'lib/underscore.string'
  string-plus: 'lib/string-plus'
  domready: 'lib/requirejs.domReady'
  foundation.core: 'foundation.core'
  foundation.abide: 'foundation.abide'
  foundation.accordion: 'foundation.accordion'
  foundation.accordionMenu: 'foundation.accordionMenu'
  foundation.drilldown: 'foundation.drilldown'
  foundation.dropdown: 'foundation.dropdown'
  foundation.dropdownMenu: 'foundation.dropdownMenu'
  foundation.equalizer: 'foundation.equalizer'
  foundation.interchange: 'foundation.interchange'
  foundation: 'foundation'
  foundation.magellan: 'foundation.magellan'
  foundation.offcanvas: 'foundation.offcanvas'
  foundation.orbit: 'foundation.orbit'
  foundation.responsiveMenu: 'foundation.responsiveMenu'
  foundation.responsiveToggle: 'foundation.responsiveToggle'
  foundation.reveal: 'foundation.reveal'
  foundation.slider: 'foundation.slider'
  foundation.sticky: 'foundation.sticky'
  foundation.tabs: 'foundation.tabs'
  foundation.toggler: 'foundation.toggler'
  foundation.tooltip: 'foundation.tooltip'
  foundation.util.box: 'foundation.util.box'
  foundation.util.keyboard: 'foundation.util.keyboard'
  foundation.util.mediaQuery: 'foundation.util.mediaQuery'
  foundation.util.motion: 'foundation.util.motion'
  foundation.util.nest: 'foundation.util.nest'
  foundation.util.timerAndImageLoader: 'foundation.util.timerAndImageLoader'
  foundation.util.touch: 'foundation.util.touch'
  foundation.util.triggers: 'foundation.util.triggers'

# DO NOT CREATE SHIMS for AMD MODULES
shim:
  jquery:
    exports: 'jQuery'
  angular:
    exports: 'angular'
  lodash:
    exports: '_'
  mithril:
    exports: 'm'
    deps:
      - es6shim
  jquery.textcomplete:
    deps:
      - jquery
  string:
    exports: 's'
  es6shim:
    deps:
      - es5shim
  foundation.core:
    deps:
      - jquery
  foundation.abide:
    deps:
    - foundation.core
  foundation.accordion:
    deps:
    - foundation.util.keyboard
    - foundation.util.motion
    - foundation.core
  foundation.accordionMenu:
    deps:
    - foundation.util.keyboard
    - foundation.util.motion
    - foundation.util.nest
    - foundation.core
  foundation.drilldown:
    deps:
    - foundation.util.keyboard
    - foundation.util.motion
    - foundation.util.nest
    - foundation.core
  foundation.dropdown:
    deps:
    - foundation.util.keyboard
    - foundation.util.box
    - foundation.util.triggers
    - foundation.core
  foundation.dropdownMenu:
    deps:
    - foundation.util.keyboard
    - foundation.util.box
    - foundation.util.nest
    - foundation.core
  foundation.equalizer:
    deps:
    - foundation.core
  foundation.interchange:
    deps:
    - foundation.util.mediaQuery
    - foundation.util.timerAndImageLoader
    - foundation.core
  foundation:
    deps:
    - foundation.core
  foundation.magellan:
    deps:
    - foundation.core
  foundation.offcanvas:
    deps:
    - foundation.util.mediaQuery
    - foundation.util.triggers
    - foundation.util.motion
    - foundation.core
  foundation.orbit:
    deps:
    - foundation.util.keyboard
    - foundation.util.motion
    - foundation.util.timerAndImageLoader
    - foundation.util.touch
    - foundation.core
  foundation.responsiveMenu:
    deps:
    - foundation.util.triggers
    - foundation.util.mediaQuery
    - foundation.util.accordionMenu
    - foundation.util.drilldown
    - foundation.util.dropdown-menu
    - foundation.core
  foundation.responsiveToggle:
    deps:
    - foundation.util.mediaQuery
    - foundation.core
  foundation.reveal:
    deps:
    - foundation.util.keyboard
    - foundation.util.box
    - foundation.util.triggers
    - foundation.util.mediaQuery
    - foundation.util.motion
    - foundation.core
  foundation.slider:
    deps:
    - foundation.util.motion
    - foundation.util.triggers
    - foundation.util.keyboard
    - foundation.util.touch
    - foundation.core
  foundation.sticky:
    deps:
    - foundation.util.triggers
    - foundation.util.mediaQuery
    - foundation.core
  foundation.tabs:
    deps:
    - foundation.util.keyboard
    - foundation.util.timerAndImageLoader if tabs contain images
    - foundation.core
  foundation.toggler:
    deps:
    - foundation.util.motion
    - foundation.core
  foundation.tooltip:
    deps:
    - foundation.util.box
    - foundation.util.triggers
    - foundation.core
  foundation.util.box:
    deps:
    - foundation.core
  foundation.util.keyboard:
    deps:
    - foundation.core
  foundation.util.mediaQuery:
    deps:
    - foundation.core
  foundation.util.motion:
    deps:
    - foundation.core
  foundation.util.nest:
    deps:
    - foundation.core
  foundation.util.timerAndImageLoader:
    deps:
    - foundation.core
  foundation.util.touch:
    deps:
    - foundation.core
  foundation.util.triggers:
    deps:
    - foundation.core

# our modules
modules:
  - name: "single_page_apps/pipeline_configs"
  - name: "single_page_apps/agents"
